name: pages
on:
  push:
  workflow_dispatch:
permissions:
  id-token: write
  pages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: jdk
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: temurin
        cache: gradle
    - name: gradle
      run: ./gradlew build
    - name: upload
      uses: actions/upload-pages-artifact@v3
      with:
        path: build/libs
    - name: deploy
      uses: actions/deploy-pages@v4
